version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  main_clone:
    title: Clone repo
    type: git-clone
    stage: prepare
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    git: github
  bump_version:
    title: Bump version
    image: jbadeau/release-it
    stage: prepare
    commands:
      - release-it --no-git
      - cf_export VERSION=$(cat VERSION)
  build:
    title: Build repo
    type: freestyle
    stage: build
    image: maven:3.6.3-openjdk-16-slim
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package