version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  main_clone:
    title: Clone repo
    type: git-clone
    stage: prepare
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    git: github
  download_dependencies:
    title: Download dependencies
    image: 15.2.1-alpine3.10
    stage: prepare
    commands:
      - yarn
  calculate_version:
    title: Calculate version
    image: alpine:3.12.1
    stage: prepare
    commands:
      - cf_export VERSION=$(cat VERSION)
  build:
    title: Build repo
    type: freestyle
    stage: build
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package