version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  main_clone:
    title: Clone repo
    type: git-clone
    stage: prepare
    repo: 'https://github.com/jbadeau/xray-report.git'
    revision: 'jira-cloud'
    git: github
  bump_version:
    title: Bump version
    image: jbadeau/release-it
    stage: prepare
    commands:
      - release-it
      - cf_export VERSION=$(cat VERSION)
  build:
    title: Build repo
    image: maven:3.6.3-openjdk-16-slim
    stage: build
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
  release:
    title: Release
    image: jbadeau/release-it
    stage: build
    commands:
      - release-it
      - cf_export VERSION=$(cat VERSION)

