version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  get_git_token:
    title: Reading Github token
    image: codefresh/cli
    stage: prepare
    commands:
      - cf_export GITHUB_TOKEN=$(codefresh get context github --decrypt -o yaml | yq -y .spec.data.auth.password)
  main_clone:
    title: Updating the repo
    image: alpine/git:latest
    stage: prepare
    commands:
      - git clone https://jbadeau:$GITHUB_TOKEN@github.com/jbadeau/xray-report.git
      - cd xray-report && git remote rm origin
      - git config --global user.name "jbadeau"
      - git config --global user.email "jose.badeau@gmail.com"
      - git remote add origin https://jbadeau:$GITHUB_TOKEN@github.com/jbadeau/xray-report.git
  bump_version:
    title: Bump version
    image: jbadeau/release-it
    stage: prepare
    commands:
      - release-it --no-git
      - cf_export VERSION=$(cat VERSION)
  build:
    title: Build repo
    image: maven:3.6.3-openjdk-16-slim
    stage: build
    commands:
      - mvn package -Drevison=$VERSION -Dmaven.repo.local=/codefresh/volume/m2_repository
  release:
    title: Release version
    image: jbadeau/release-it
    stage: build
    commands:
      - git config --global credential.helper store
      - git config --global user.email "jose.badeau@gmail.com"
      - git config --global user.name "jbadeau"
      - release-it

